version: '3'

services:
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:alpine
    volumes:
      - ../:/var/www:delegated
      - ./nginx/:/etc/nginx/conf.d:delegated
      - ./nginx/vhosts:/etc/nginx/vhosts:delegated
      - ./nginx/logs:/var/log/nginx:delegated
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    container_name: ${APP_NAME}_php_fpm
    build:
      context: php-fpm
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www:delegated
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:delegated
      - ~/.ssh:/home/www-data/.ssh:delegated
    environment:
      - CONTAINER_ROLE=php-fpm
    depends_on:
      - database

  database:
    container_name: ${APP_NAME}_mysql
    image: library/mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker    

